### ISSUE TITLE
Homolofy REST endpoints

### ISSUE THREAD

**Issue by muffato** [Ensembl/plant_tools#14]
Two possible modifications
1. Taxon names can be used, e.g.
    ```
    my $target_clade=Poaceae;
    ```
    https://github.com/Ensembl/plant_tools/blob/c401a2d0864f2fe8d3cae341690230a2c9ec98cf/demo_scripts/exampleREST.pl#L181
2. `homology/id/` could be used since `TraesCS1B02G1952001` is a stable_id, and you don't need to provide the species name
    https://github.com/Ensembl/plant_tools/blob/c401a2d0864f2fe8d3cae341690230a2c9ec98cf/demo_scripts/exampleREST.pl#L186

**Comment by brunocontrerasmoreira** [comment]
Actually I don't think it hurts to set the species specifically in the context on the upcoming strains with lifted over genes
