### ISSUE TITLE
MySQL query to fetch homoeologues

### ISSUE THREAD

**Issue by muffato** [Ensembl/plant_tools#15]
Hi,

The recommended way is to grab the `method_link_species_set_id` and use that as a filter in the `homology` table
https://github.com/Ensembl/plant_tools/blob/c401a2d0864f2fe8d3cae341690230a2c9ec98cf/demo_scripts/exampleMySQL.sh#L88-L106
Not only it saves a join, MySQL was somehow unable to use indexes for the previous query, so had to scan _every_ homology and then join and filter. By using `method_link_species_set_id` it can use the index directly, which is way faster

**Comment by brunocontrerasmoreira** [comment]
Thanks for the suggestion, can you write the actual updated query? Perhaps you can do a PR
